/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import java.awt.Component;
import java.io.File;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import static sun.audio.AudioPlayer.player;

/**
 *
 * @author juan
 */
public class VentanaInternaJMFPlayer extends javax.swing.JInternalFrame {

    
    private Player player = null;
    
    
    
    
    /**
     * Creates new form VentanaInternaJMFPlayer
     */       
    private VentanaInternaJMFPlayer(File f) {
        initComponents();
        String sfichero = "file:" + f.getAbsolutePath();
        System.out.println(sfichero);
        MediaLocator ml = new MediaLocator(sfichero);
        try {
            player = Manager.createRealizedPlayer(ml);
            Component vc = player.getVisualComponent();
            if(vc!=null)add(vc, java.awt.BorderLayout.CENTER);
            Component cpc = player.getControlPanelComponent();
            if(cpc!=null)add(cpc, java.awt.BorderLayout.SOUTH);
            this.pack();
        }catch(Exception e) {
            System.err.println("VentanaInternaJMFPlayer: "+e);
            player = null;
        }
        this.resizable=true;
        this.closable=true;
        this.maximizable=true;
        
    }
        public static VentanaInternaJMFPlayer getInstance(File f){
            VentanaInternaJMFPlayer v = new VentanaInternaJMFPlayer(f);
            if(v.player!=null) 
                return v;
            else 
                return null;
        }
        public void play() {
            if (player != null) {
                try {
                    player.start();
                } catch (Exception e) {
                    System.err.println("VentanaInternaJMFPlayer: "+e);
                }
            }
        }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
