/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.jaf.iu;

import static extras.Imprimir.Imprimir;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Point2D;
import java.awt.image.BufferedImage;
import sm.jaf.graficos.Figura;
import sm.jaf.graficos.Rectangulo;

/**
 *
 * @author juan
 * 
 * 
 * Lienzo2DImagen extiende de Lienzo2D porque debe tener todas las caracteríticas propias del Lienzo2D además de las 
 * que esta clase añada. Por eso una instancia de esta podrá hacer todo lo que hacía el padre, tendrá todos sus métodos 
 * y serán accesibles todas sus variables siempre a través de los métodos set/get. Así esta nueva imagen se centrará a todo lo relativo 
 * a la imagen.
 * 
 * 
 */
public class Lienzo2DImagen extends Lienzo2D {

    //Variable que almacernará los datos de la imagen.
    private BufferedImage imagen;
    
    
    
    
    /**
     * Creates new form Lienzo2DImagen
     */
    public Lienzo2DImagen() {
        initComponents();        
    }

    
    public void setImage(BufferedImage img){
        Imprimir("INTRODUCIENDO IMAGEN EN LIENZO2diMAGEN");
        this.imagen= img;
        
        //Ajustamos el tamaño del lienzo al tamaño de la imagen que abrimos.
        if(img!=null){
            setPreferredSize(new Dimension(img.getWidth(), img.getHeight()));
        }
            
    }
    
    
    public BufferedImage getImage(boolean drawVector){
        if(drawVector){
            return getImage();
        }
        else
            return getImage();
    }
            
    
    public BufferedImage getImage(){
        Imprimir("Llamando a getImage en Lienzo2DImagen");
       
        if(!vShape.isEmpty()){
            return dibujarFiguras();
        }
        
        return imagen;          
    }
    
    public BufferedImage dibujarFiguras(){
        //Intentando dibujar figuras en imagen
        
        
        if(imagen==null){
            Imprimir("Aun no hay una imgaen donde guardar!");
            crearImagen();
            
            paint(imagen.createGraphics());  //1ª forma de dibujar las formas que no funcionaba
            return imagen;// 1ª forma que no funcionaba
            
        }else{
            Imprimir("La imagen ya tiene contenido");
        
        
        
        //paint(imagen.createGraphics());     
        
        BufferedImage mImagen;
        Dimension d = getSize();
        int ancho = d.width, alto = d.height;
        mImagen = new BufferedImage(ancho,alto, BufferedImage.TYPE_INT_RGB);
        
        //Tenemos que convertir esta imagen en blanca:
        

        
        Graphics2D gOculta = mImagen.createGraphics();
        
      //  gOculta.setPaint(Color.WHITE);
      //  gOculta.drawRect(0, 0, alto, ancho);
        
        gOculta.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        gOculta.drawImage(imagen, 0, 20, this);
        
        if(!vShape.isEmpty())
            for(Figura figura:vShape)
                figura.dibujateEn(gOculta);
        
        return mImagen;
        }
    
      //  return imagen; 1ª forma que no funcionaba
    }
    
    
    public void crearImagen(){
        Dimension d = getSize();
        int ancho = d.width; int alto = d.height;
        imagen = new BufferedImage(ancho, alto, BufferedImage.TYPE_INT_RGB);
    }
    
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(imagen!=null)
            g.drawImage(imagen, 0, 0, this);
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}
