package extras;

import static extras.Imprimir.Imprimir;
import java.awt.GraphicsEnvironment;
import java.awt.geom.Point2D;
import javax.swing.DefaultComboBoxModel;
import sm.jaf.graficos.Texto;
import sm.jaf.iu.Lienzo2D;

/**
 *
 * @author Juan A. Fernández Sánchez
 */
public final class herramientaTexto extends javax.swing.JFrame {

    
    /**
     * Variable de referencia al padre de esta ventana.
     */
    private Lienzo2D padre;
    
    /**
     * Punto de escritura exacto en el lienzo padre.
     */
    private Point2D puntoEscritura;


    /**
     * Vector de fuentes del sistema.
     */     
    private String[] fuentesSistema;
    
    
    /**
     * Variable texto temporal.    
     */
    private Texto texto;
    
    /**
     * Texto contenido dentro del campo de texto al inicio.
     */
    String textoInicio;
    
    
    /**
     * Constructor    
     * @param padre //Le pasamos el propio padre que lo crea para acceder forma fácil a métodos de este.     
     * @param puntoLienzo     
     */
    public herramientaTexto(Lienzo2D padre, Point2D puntoLienzo) {
        initComponents();
     
        
        //Cargamos las fuentes del sistema:
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        fuentesSistema = ge.getAvailableFontFamilyNames();
        
        //Las pasamos al comboBoxFuentesSistema:
        comboBoxFuentesSistema.setModel(new DefaultComboBoxModel(fuentesSistema));
                
        
        
        //Creamos la referencia al padre.
        this.padre=padre;
        
        //Referenciamos al punto exacto donde se marcó en el lienzo el padre.
        puntoEscritura=puntoLienzo;
      
        
        //Seteamos el grosor en la herramienta por defecto:
        spinnerGrosor.setValue(40);
        textoInicio="Escriba aquí!";
        
        
        //Seteamos el texto por defecto:

        texto = new Texto();
        
        texto.setGrosor((int)spinnerGrosor.getValue());
        texto.setPosicion(puntoEscritura);
        texto.setFuente("Arial");
        texto.setText(textoInicio);
        
        
        padre.setTexto(texto);
        
        
        
        
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        System.out.println("Cerrando  ventana");

    }
});
        
    }

    
    public herramientaTexto(Lienzo2D padre, Texto textoAModificar){
        
        Imprimir("Modificando texto: "+textoAModificar.getText());
        
        //Inicializamos los componentes gráficos de la herramienta.
        initComponents();
        
        //Cargamos las fuentes del sistema:
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        fuentesSistema = ge.getAvailableFontFamilyNames();
        
        //Las pasamos al comboBoxFuentesSistema:
        comboBoxFuentesSistema.setModel(new DefaultComboBoxModel(fuentesSistema));
                
        
        
        //Creamos la referencia al padre.
        this.padre=padre;
        
        //Creamos la referencia al padre.
        this.padre=padre;
        //Inicializamos nuestra variable privada
        texto = new Texto();
        
        texto=textoAModificar;
        
        //Introducimos en el campo de texto el string del texto que nos viene por el constructor.
        campoTexto.setText(texto.getText());
        
        //Modificamos el spinner del tamaño del texto al tamaño que tenga el que nos pasan:
        spinnerGrosor.setValue(texto.getGrosor());
    }
    
    /**
     * Con esta función reseteamos la herramienta y dejamos la imagen como estaba al principio.
     */
    private void resetHerramienta(){
                 
               
    }
    
   
    
    
    private void aplicar(){

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesTipo = new javax.swing.ButtonGroup();
        grupoBotonesMatriz = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxFuentesSistema = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        spinnerGrosor = new javax.swing.JSpinner();
        campoTexto = new javax.swing.JTextField();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel4.setText("Fuente");

        comboBoxFuentesSistema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxFuentesSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxFuentesSistemaActionPerformed(evt);
            }
        });

        jLabel6.setText("Grosor");

        spinnerGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerGrosorStateChanged(evt);
            }
        });

        campoTexto.setText("Escriba aquí:");
        campoTexto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                campoTextoCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(campoTexto))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxFuentesSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboBoxFuentesSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(spinnerGrosor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(campoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerGrosorStateChanged
        Imprimir("Cambiand estado spinner: "+spinnerGrosor.getValue().toString());
        if((int)spinnerGrosor.getValue()==0)
            spinnerGrosor.setValue(1);
            
        //Sacamos el texto del padre y le cambiamos el grosor:
        if(!padre.isEmptyTextos()){
            padre.getLastTexto().setGrosor((int)spinnerGrosor.getValue());
            padre.repaint();
        }
        
        
    }//GEN-LAST:event_spinnerGrosorStateChanged

    private void campoTextoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_campoTextoCaretUpdate
      Imprimir("Contendio del campo de texto: "+campoTexto.getText());
      textoInicio=campoTexto.getText();
       if(!padre.isEmptyTextos()){
            padre.getLastTexto().setText(textoInicio);
            padre.repaint();
        }
    }//GEN-LAST:event_campoTextoCaretUpdate

    private void comboBoxFuentesSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFuentesSistemaActionPerformed
        String fuente=(String)comboBoxFuentesSistema.getSelectedItem();
        if(!padre.isEmptyTextos()){
            padre.getLastTexto().setFuente(fuente);
            padre.repaint();
        }
       
    }//GEN-LAST:event_comboBoxFuentesSistemaActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTexto;
    private javax.swing.JComboBox comboBoxFuentesSistema;
    private javax.swing.ButtonGroup grupoBotonesMatriz;
    private javax.swing.ButtonGroup grupoBotonesTipo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner spinnerGrosor;
    // End of variables declaration//GEN-END:variables
}
