/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import static extras.Imprimir.Imprimir;
import java.awt.Color;
import extras.Herramienta;

/**
 *
 * @author juan
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    
       static int contadorVentanas = 0;
  //  static final int xOffset = 30, yOffset = 30;
    
    /**
     * Creates new form VI
     */
    public VentanaInterna() {
        super("Sin título " + (++contadorVentanas),true,true,true,true);
        initComponents();                       
    }

    public void setHerramienta(Herramienta herramienta){
        miLienzo2D.setTipoHerramienta(herramienta);
    }
    
     //Set de color
    public void setColor(Color color){
        miLienzo2D.setColor(color);
    }
        
    public void setModoSeleccion(boolean modo){
        miLienzo2D.setModoSeleccion(modo);            
    }
    public void setGrosor(int grosor){
        miLienzo2D.setGrosor(grosor);
    }
    
    public void setRelleno(boolean relleno){
        miLienzo2D.setRelleno(relleno);
    }
    public void setMejoraRenderizacion(boolean mejora){
        miLienzo2D.setMejoraRenderizacion(mejora);
    }
    public void setTransparencia(boolean transparencia){
        miLienzo2D.setTransparencia(transparencia);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miLienzo2D = new sm.jaf.iu.Lienzo2D();

        javax.swing.GroupLayout miLienzo2DLayout = new javax.swing.GroupLayout(miLienzo2D);
        miLienzo2D.setLayout(miLienzo2DLayout);
        miLienzo2DLayout.setHorizontalGroup(
            miLienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        miLienzo2DLayout.setVerticalGroup(
            miLienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        getContentPane().add(miLienzo2D, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.jaf.iu.Lienzo2D miLienzo2D;
    // End of variables declaration//GEN-END:variables
}
