/*
 * Copyright (C) 2015 Juan A. Fernández Sánchez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package accesorios;

import Programa.VentanaInterna;
import Programa.VentanaPrincipal;
import extras.Herramienta;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.ItemSelectable;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;

/**
 *
 * @author Juan Antonio Fernández Sánchez 
 */
public class nuevoLienzo extends javax.swing.JFrame {

    
    private final VentanaPrincipal padre;
    
    //Tamaño del lienzo en píxeles
    private int anchoLienzo;
    private int altoLienzo;
    
 
    
    /**
     * Constructor de la clase 
     * @param padre VentanaPrincipal padre que se le pasa para poder enviarle mensajes directamente.
     */
    public nuevoLienzo(VentanaPrincipal padre) {                         

        this.padre=padre;
        
        //Valores por defecto de ancho y alto del lienzo:
            anchoLienzo=300;
            altoLienzo=300;
            
        initComponents();    
            
        //Ajustamos el aspecto de los spinners colocandoles el valor.
        actualizaSpinner();
        

        
        //Ajustamos el comboBox
        comboPlantilla.removeAllItems();
        comboPlantilla.addItem("Basic");
        comboPlantilla.addItem("A5");
        comboPlantilla.addItem("A4");

        
        ItemListener itemListener = new ItemListener() {
            public void itemStateChanged(ItemEvent itemEvent) {
                     
                Object item=itemEvent.getItem();
                if(item=="A4"){
                    altoLienzo=3508; anchoLienzo=2480; actualizaSpinner();                    
                }else if(item=="A5"){
                    altoLienzo=2480; anchoLienzo=1748; actualizaSpinner(); 
                }else if(item=="Basic"){
                    altoLienzo=400; anchoLienzo=400; actualizaSpinner(); 
                }             
            }
        };
        
        
        comboPlantilla.addItemListener(itemListener);
        
        //Nos colocamos en el centro de la pantalla
        this.setLocationRelativeTo(null);
        
    }
    
    public void actualizaSpinner(){
        this.spinnerAlto.setValue(altoLienzo);
        this.spinnerAncho.setValue(anchoLienzo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        comboPlantilla = new javax.swing.JComboBox();
        panelTamañoImagen = new javax.swing.JPanel();
        spinnerAlto = new javax.swing.JSpinner();
        spinnerAncho = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear nuevo lienzo");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setText("Plantilla:");

        comboPlantilla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPlantillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(comboPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        spinnerAlto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAltoStateChanged(evt);
            }
        });

        spinnerAncho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerAnchoStateChanged(evt);
            }
        });

        jLabel4.setText("Ancho:");

        jLabel5.setText("Alto:");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel8.setText("Tamaño de la imagen:");

        javax.swing.GroupLayout panelTamañoImagenLayout = new javax.swing.GroupLayout(panelTamañoImagen);
        panelTamañoImagen.setLayout(panelTamañoImagenLayout);
        panelTamañoImagenLayout.setHorizontalGroup(
            panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTamañoImagenLayout.createSequentialGroup()
                .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTamañoImagenLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelTamañoImagenLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        panelTamañoImagenLayout.setVerticalGroup(
            panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTamañoImagenLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTamañoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelTamañoImagen, java.awt.BorderLayout.CENTER);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(botonAceptar)
                .addGap(42, 42, 42)
                .addComponent(botonCancelar)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addContainerGap())
        );

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPlantillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPlantillaActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
       
        //Al pulsar sobre el boton aceptar.
        
            //1º Se crea una variable imagen:
               BufferedImage img;
            //2º Se incializa con una imagen del tamaño seleciconado por el usuario:
               System.out.println("ancho"+anchoLienzo+"alto"+altoLienzo);
               img=new BufferedImage(anchoLienzo,altoLienzo,BufferedImage.TYPE_INT_RGB);
               
            // 2.2 Abría que ajustar el color de la nueva imagen que se está creando rellenando la imagen que se crea.
               Graphics objetoGrafico = img.getGraphics();
               objetoGrafico.setColor(padre.getColorLiezoDefecto());
               objetoGrafico.fillRect(0,0, anchoLienzo, altoLienzo);
               
               
            //3º Se introduce en la ventanaInterna
               VentanaInterna ventanaInterna;
               ventanaInterna=new VentanaInterna(padre);
               
               ventanaInterna.getLienzo().setTipoHerramienta(padre.herramienta);
               
               //Aplicamos el estilo de trazo que tiene por defecto el padre.
               ventanaInterna.getLienzo().setTrazo(padre.getTrazoDefecto());
               
               //Aplicamos el estilo de relleno que tiene el padre en su variable por defecto:
               ventanaInterna.getLienzo().setRelleno(padre.getRellenoDefecto());
               if(padre.rellenoActivo)
                ventanaInterna.getLienzo().setRelleno(true);
               else
                ventanaInterna.getLienzo().setRelleno(false);
               
               
               ventanaInterna.getLienzo().setMejoraRenderizacion(true);
               ventanaInterna.getLienzo().setImage(img);
            //4º Se introduce esa ventana nueva en el panel y la hacemos visible
                //Añadimos la ventana interna al objeto de tipo JDesktopPane
                padre.getPanelEscritorio().add(ventanaInterna);            
                //La hacemos visible:
                ventanaInterna.setVisible(true);
            
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * Programación del comportamiento ante el cambio de estado del spinnerAncho
     * @param evt 
     */
    private void spinnerAnchoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAnchoStateChanged
     
        //Se obtiene el valor del spinner y se graba en anchoLienzo
        anchoLienzo=(int)spinnerAncho.getValue();
        //Se controla que pueda ser inferior a 1
        if(anchoLienzo<=0){
            anchoLienzo=1;
            //No se deja bajar de 1 el valor.
            spinnerAncho.setValue(anchoLienzo);            
        }        
    }//GEN-LAST:event_spinnerAnchoStateChanged

    /**
     * Programacion del comportamiento igual al spinnerAncho pero con la variable spinnerAlto
     * @param evt 
     */
    private void spinnerAltoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerAltoStateChanged
        altoLienzo=(int)spinnerAlto.getValue();
        if(altoLienzo<=0){
            altoLienzo=1;
            spinnerAlto.setValue(altoLienzo);            
        }        
    }//GEN-LAST:event_spinnerAltoStateChanged

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox comboPlantilla;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelTamañoImagen;
    private javax.swing.JSpinner spinnerAlto;
    private javax.swing.JSpinner spinnerAncho;
    // End of variables declaration//GEN-END:variables
}
