package Programa;

import static extras.Imprimir.Imprimir;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Paint;
import java.awt.event.WindowEvent;
import java.awt.geom.Point2D;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JSpinner;
import sm.jaf.graficos.Linea;
import sm.jaf.graficos.Rectangulo;
import sm.jaf.graficos.Relleno;
import sm.jaf.graficos.Relleno.Horientacion;
import sm.jaf.graficos.Trazo;

/**
 * Herramienta de ajuste de trazado.
 * Esta clase confeccionará un tipo de trazado para la linea. Pero ojo, el grosor de la linea lo cogerá del actual
 * de la ventana activa.
 * @author Juan A. Fernández Sánchez
 */
public final class herramientaRelleno extends javax.swing.JFrame {

    
    private VentanaPrincipal padre;
    
    private VentanaInterna vis;

    Paint relleno;
    Rectangulo rectangulo;

    Point2D a = new Point2D.Double(0,0);
    Point2D b = new Point2D.Double(400,50);
    
    Point2D aCentrado = new Point2D.Double(0,25);
    Point2D bCentrado = new Point2D.Double(400,25);
    
    
    //Prueba de la clase relleno:
    Relleno prueba;
    
    Relleno miRelleno;
    

    /**sl
     * Constructor    
     * @param padre //Le pasamos el propio padre que lo crea para acceder forma fácil a métodos de este.     
     */
    @SuppressWarnings("empty-statement")
    public herramientaRelleno(VentanaPrincipal padre) {
        initComponents();
                                    
        //Creamos la referencia al padre
        this.padre=padre;
 
        
        /**
         * Rescatando los valores del relleno por defecto del padre.
         */
        
        Relleno rellenoDefectoPadre = padre.getRellenoDefecto();
        
            botonColorA.setBackground(rellenoDefectoPadre.getColorA());
            botonColorB.setBackground(rellenoDefectoPadre.getColorB());
            
            if(rellenoDefectoPadre.getHorientacion()==Horientacion.VERTICAL)
                this.botonVertical.setSelected(true);
            if(rellenoDefectoPadre.getHorientacion()==Horientacion.HORIZONTAL)
                this.botonHorizontal.setSelected(true);
            if(rellenoDefectoPadre.getHorientacion()==Horientacion.DIAGONAL_A)
                this.botonDiagonal1.setSelected(true);
            if(rellenoDefectoPadre.getHorientacion()==Horientacion.DIAGONAL_B)
                this.botonDiagonal2.setSelected(true);
        
        
        
        miRelleno = new Relleno(padre.getRellenoDefecto().getColorA(), padre.getRellenoDefecto().getColorB(), padre.getRellenoDefecto().getHorientacion());
        
        

        
        
        rectangulo = new Rectangulo();
        rectangulo.cambiarPosicion(a, b);
        

        
        
         //Simple: sólo de un color
        rectangulo.setRelleno(miRelleno);
        rectangulo.setRelleno(true);
        
      //  rectangulo.setRelleno(new Relleno(Color.PINK, Color.BLUE, Horientacion.VERTICAL));
        
        lienzoPrev.addFigure(rectangulo);
        lienzoPrev.repaint();
        
        

        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        System.out.println("Cerrando ventana");
        
    }
});
        
    }

   
  
  
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesOrientacion = new javax.swing.ButtonGroup();
        panelNorte = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lienzoPrev = new sm.jaf.iu.Lienzo2D();
        textPrevisualizacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonColorA = new javax.swing.JButton();
        botonColorB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonHorizontal = new javax.swing.JToggleButton();
        botonVertical = new javax.swing.JToggleButton();
        botonDiagonal1 = new javax.swing.JToggleButton();
        botonDiagonal2 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        panelNorte.setBackground(new java.awt.Color(145, 145, 145));

        jLabel1.setFont(new java.awt.Font("Sawasdee", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ajustes de relleno");

        exitButton.setBackground(new java.awt.Color(255, 135, 135));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel.png"))); // NOI18N
        exitButton.setPreferredSize(new java.awt.Dimension(40, 40));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(255, 219, 147));
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reset.png"))); // NOI18N
        resetButton.setPreferredSize(new java.awt.Dimension(40, 40));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(168, 255, 168));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png"))); // NOI18N
        saveButton.setPreferredSize(new java.awt.Dimension(40, 40));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/settings.png"))); // NOI18N

        javax.swing.GroupLayout panelNorteLayout = new javax.swing.GroupLayout(panelNorte);
        panelNorte.setLayout(panelNorteLayout);
        panelNorteLayout.setHorizontalGroup(
            panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNorteLayout.setVerticalGroup(
            panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2))
            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel1)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelNorte, java.awt.BorderLayout.PAGE_START);

        lienzoPrev.setBackground(javax.swing.UIManager.getDefaults().getColor("ArrowButton.background"));

        javax.swing.GroupLayout lienzoPrevLayout = new javax.swing.GroupLayout(lienzoPrev);
        lienzoPrev.setLayout(lienzoPrevLayout);
        lienzoPrevLayout.setHorizontalGroup(
            lienzoPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        lienzoPrevLayout.setVerticalGroup(
            lienzoPrevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        textPrevisualizacion.setFont(new java.awt.Font("Sawasdee", 1, 18)); // NOI18N
        textPrevisualizacion.setText("Previsualización:");

        jLabel3.setText("Degradado:");

        botonColorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorAActionPerformed(evt);
            }
        });

        botonColorB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColorBActionPerformed(evt);
            }
        });

        jLabel4.setText("Color A:");

        jLabel5.setText("Color B:");

        grupoBotonesOrientacion.add(botonHorizontal);
        botonHorizontal.setSelected(true);
        botonHorizontal.setText("-");
        botonHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHorizontalActionPerformed(evt);
            }
        });

        grupoBotonesOrientacion.add(botonVertical);
        botonVertical.setText("I");
        botonVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerticalActionPerformed(evt);
            }
        });

        grupoBotonesOrientacion.add(botonDiagonal1);
        botonDiagonal1.setText("/");
        botonDiagonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDiagonal1ActionPerformed(evt);
            }
        });

        grupoBotonesOrientacion.add(botonDiagonal2);
        botonDiagonal2.setText("\\");
            botonDiagonal2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonDiagonal2ActionPerformed(evt);
                }
            });

            jLabel6.setText("Horientación:");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lienzoPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textPrevisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonColorA)
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonColorB))
                                .addComponent(jLabel3))
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(botonHorizontal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonVertical)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonDiagonal1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonDiagonal2)))))
                    .addContainerGap(199, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonColorA, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(botonColorB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonHorizontal)
                                        .addComponent(botonVertical)
                                        .addComponent(botonDiagonal1)
                                        .addComponent(botonDiagonal2))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textPrevisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lienzoPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(jLabel5)))
                    .addGap(25, 25, 25))
            );

            getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

            pack();
        }// </editor-fold>//GEN-END:initComponents


    
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
                               
    }//GEN-LAST:event_resetButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        //Hace exactamente lo mismo que darle al boton cerrar de la esquina superior izquierda, es decir llamar a recuperarImagen.
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_exitButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        padre.setRellenoDefecto(miRelleno);
        
        if(padre.getPanelEscritorio().getSelectedFrame()!=null){
            ((VentanaInterna)padre.getPanelEscritorio().getSelectedFrame()).getLienzo().setRelleno(miRelleno);
        }
        
        //Cerramos la ventana
        this.dispose();
                
    }//GEN-LAST:event_saveButtonActionPerformed

    private void botonColorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorAActionPerformed
       
        //Escogemos el nuevo color con la herramienta JColorChooser
            JColorChooser ventanaDeColores=new JColorChooser();
            Color color=ventanaDeColores.showDialog(null, "Seleccione un Color", Color.WHITE);
            botonColorA.setBackground(color);
        
        //Lo aplicamos al degradado:
            // relleno=new GradientPaint(aCentrado, botonColorA.getBackground(), bCentrado, botonColorB.getBackground());
        
           //  ((Rectangulo)lienzoPrev.getFigura(0)).rellenoComplejo=relleno;
             rectangulo.getRellenoComplejo().setColorA(color);
             
             lienzoPrev.repaint();
        
       // Color color=botonColorA.getBackground();
        
 
        
    }//GEN-LAST:event_botonColorAActionPerformed

    private void botonColorBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColorBActionPerformed
          //Escogemos el nuevo color con la herramienta JColorChooser
            JColorChooser ventanaDeColores=new JColorChooser();
            Color color=ventanaDeColores.showDialog(null, "Seleccione un Color", Color.WHITE);
            botonColorB.setBackground(color);
        
        //Lo aplicamos al degradado:
           //  relleno=new GradientPaint(aCentrado, botonColorA.getBackground(), bCentrado, botonColorB.getBackground());
        
             //((Rectangulo)lienzoPrev.getFigura(0)).rellenoComplejo=relleno;
            rectangulo.getRellenoComplejo().setColorB(color);
             lienzoPrev.repaint();
    }//GEN-LAST:event_botonColorBActionPerformed

    private void botonHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHorizontalActionPerformed
        
        //Creamos el gradiente con los valores por defecto
           // relleno=new GradientPaint(aCentrado, botonColorA.getBackground(), bCentrado, botonColorB.getBackground());
        
        //Lo aplicamos a la figura de la previsualización:
          //   ((Rectangulo)lienzoPrev.getFigura(0)).rellenoComplejo=relleno;
            rectangulo.getRellenoComplejo().setHorientacion(Horientacion.HORIZONTAL);
             
        //Repintamos el ienzo
             lienzoPrev.repaint();
    }//GEN-LAST:event_botonHorizontalActionPerformed

    private void botonVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerticalActionPerformed
             
        //Creamos dos nuevos puntos para el degradado
             Point2D superior = new Point2D.Double(200,0);
             Point2D inferior = new Point2D.Double(200,50);
        
        //Construimos el degradado
             //relleno=new GradientPaint(superior, botonColorA.getBackground(), inferior, botonColorB.getBackground());
        
        //Lo aplicamos a la figura de la previsualización:
            // ((Rectangulo)lienzoPrev.getFigura(0)).rellenoComplejo=relleno;
             rectangulo.getRellenoComplejo().setHorientacion(Horientacion.VERTICAL);
             
        //Repintamos el ienzo
             lienzoPrev.repaint();
    }//GEN-LAST:event_botonVerticalActionPerformed

    private void botonDiagonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiagonal1ActionPerformed
        //Creamos dos nuevos puntos para el degradado
             Point2D superior = new Point2D.Double(0,50);
             Point2D inferior = new Point2D.Double(200,0);
        
        //Construimos el degradado
             relleno=new GradientPaint(superior, botonColorA.getBackground(), inferior, botonColorB.getBackground());
        
        //Lo aplicamos a la figura de la previsualización:
            // ((Rectangulo)lienzoPrev.getFigura(0)).rellenoComplejo=relleno;
             rectangulo.getRellenoComplejo().setHorientacion(Horientacion.DIAGONAL_A);
             
        //Repintamos el ienzo
             lienzoPrev.repaint();
    }//GEN-LAST:event_botonDiagonal1ActionPerformed

    private void botonDiagonal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiagonal2ActionPerformed
                //Creamos dos nuevos puntos para el degradado
             Point2D superior = new Point2D.Double(0,0);
             Point2D inferior = new Point2D.Double(200,50);
        
        //Construimos el degradado
             relleno=new GradientPaint(superior, botonColorA.getBackground(), inferior, botonColorB.getBackground());
                     
        //Lo aplicamos a la figura de la previsualización:
             //((Rectangulo)lienzoPrev.getFigura(0)).rellenoComplejo=relleno;
             rectangulo.getRellenoComplejo().setHorientacion(Horientacion.DIAGONAL_B);
             
        //Repintamos el ienzo
             lienzoPrev.repaint();
    }//GEN-LAST:event_botonDiagonal2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonColorA;
    private javax.swing.JButton botonColorB;
    private javax.swing.JToggleButton botonDiagonal1;
    private javax.swing.JToggleButton botonDiagonal2;
    private javax.swing.JToggleButton botonHorizontal;
    private javax.swing.JToggleButton botonVertical;
    private javax.swing.JButton exitButton;
    private javax.swing.ButtonGroup grupoBotonesOrientacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private sm.jaf.iu.Lienzo2D lienzoPrev;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel textPrevisualizacion;
    // End of variables declaration//GEN-END:variables
}
