/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programa;

import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import sm.sound.SMRecorder;
import sm.sound.SMSoundRecorder;

/**
 * Pequea GUI y herramienta incrustada para la grabación de audios.
 * Permite grabar sonidos desde el micrófono del sistema y realiza cambios en los iconos en la puesta 
 * en marcha y parada.
 * @author Juan A. Fernández Sánchez
 */
public class VentanaInternaAudioGrabador extends javax.swing.JFrame {

    SMRecorder recorder;
    
    File f;
    
    /**
     * Creates new form VentanaInternaAudio
     * @param f
     */
    public VentanaInternaAudioGrabador(File f) {
        initComponents();
        this.f=f;
        this.setTitle("Grabando "+f.getName());
        //recorder = new SMSoundRecorder(f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRec = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();

        buttonRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/RecordPressed_48x48.png"))); // NOI18N
        buttonRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRecActionPerformed(evt);
            }
        });

        buttonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/StopDisabled_48x48.png"))); // NOI18N
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonRec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonRec)
            .addComponent(buttonStop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRecActionPerformed
        
        recorder = new SMSoundRecorder(f);
        recorder.record();
        
        //Cambiamos el icono del botón de rec.
        this.buttonRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/RecordDisabled_48x48.png")));
        //Cambiamos el icono del botón de stop.
        this.buttonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/StopNormalRed_48x48.png")));
        
        
        /*
        if(recorder!=null)
            recorder.record();
        */
    }//GEN-LAST:event_buttonRecActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        //if(recorder!=null)
            recorder.stop();
                        
        //Cambiamos los iconos.
            
        //Cambiamos el icono del botón de rec.
        this.buttonRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/RecordPressed_48x48.png")));
        //Cambiamos el icono del botón de stop.
        this.buttonStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/StopDisabled_48x48.png")));
    }//GEN-LAST:event_buttonStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInternaAudioGrabador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInternaAudioGrabador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInternaAudioGrabador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInternaAudioGrabador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRec;
    private javax.swing.JButton buttonStop;
    // End of variables declaration//GEN-END:variables
}
