/*
 * Copyright (C) 2015 Juan A. Fernández Sánchez
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package Programa;

import static extras.Imprimir.Imprimir;
import java.awt.Component;
import java.io.File;
import javax.media.Format;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.Player;
import javax.media.PlugInManager;
import javax.media.format.AudioFormat;
import static sun.audio.AudioPlayer.player;

/**
 * Clase que construye una ventana de reproducción de video y audio.
 * @author Juan A. Fernández Sánchez
 */
public class VentanaInternaJMFPlayer extends javax.swing.JInternalFrame {

    /**
     * Objeto reproductor.
     * @see <a href="http://docs.oracle.com/javame/config/cdc/opt-pkgs/api/jsr927/javax/media/Player.html">Class Player</a>
     * 
     */
    public Player player = null;
    
    /**
     * Constructor de VentanaInternaJMFPlayer
     */       
    private VentanaInternaJMFPlayer(File f) {

        
        initComponents();
        
        Imprimir("Abriendo VentanaInternaJMFPlayer");
        
        
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        
        //Extraemos la ruta del fichero
        String sfichero = "file:" + f.getAbsolutePath();
        
        Imprimir("Try open: "+sfichero);
        //Le ponemos a la ventana el nombre del fichero
        this.setTitle(f.getName());
        
        System.out.println(sfichero);
        
        try {
            
            MediaLocator ml = new MediaLocator(sfichero);  
            player = Manager.createRealizedPlayer(ml);	
            Component vc = player.getVisualComponent();
            if(vc!=null)add(vc, java.awt.BorderLayout.CENTER);
            Component cpc = player.getControlPanelComponent();
            if(cpc!=null)add(cpc, java.awt.BorderLayout.SOUTH);
            this.pack();
            
           
        }catch(Exception e) {
            System.err.println("VentanaInternaJMFPlayer: "+e);            
        }
        
    }
    
    /**
     * Devuelve una instancia de la clase.
     * @param f El nombre del fichero que queremos abrir.
     * @return Un objeto de tipo VentanaInternaJMFPlayer inicializado
     */
    public static VentanaInternaJMFPlayer getInstance(File f){
        VentanaInternaJMFPlayer v = new VentanaInternaJMFPlayer(f);
        if(v.player!=null) 
            return v;
        else 
            return null;
    }
    
    /**
     * Hace que la reproducción se inicie.
     */
    public void play() {
            Imprimir("PRESS BUTTON PLAY");
        if (player != null) {
            try {
                Imprimir("Try playing");
                player.start();
            } catch (Exception e) {
                System.err.println("VentanaInternaJMFPlayer: "+e);
            }
        }
        Imprimir("PLAYER==NULL");
    }
    /**
     * Hace que la ventan de reproducción se cierre.
     */
    public void close(){
         try{
            if(player!=null) player.close();
        } catch(Exception e) {
            System.err.println("VentanaInternaJMFPlayer: " + e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
